sentence = input('Enter your sentence: ')
print(sentence)
word1 = input('Enter the word to replace:'+sentence)
word2 = input('Enter the word to replace it with:')
print(sentence.replace(word1, word2))
